# keep these in sync so we can find the grub entry matching the kernel
kernel_grep_string: '5.10.73-kafl+'
kernel_deb_urls:
  - https://github.com/IntelLabs/kafl.linux/releases/download/kvm-nyx-5.10.73/linux-image-5.10.73-kafl+_5.10.73-kafl+-1_amd64.deb
